name: Client Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build client container
        run: docker build --build-arg NODE_PORT=$FRONTEND_NODE_PORT --build-arg USER_ID=$USER_ID -t client-app .

      - name: build app
        run: docker run --rm -e NODE_PORT=$FRONTEND_NODE_PORT -e USER_ID=$USER_ID client-app bash -c "cd /app && corepack yarn install && cd /app/client && corepack yarn install && corepack yarn build"
